name: 'corvus-comment'
description: 'Generate a comment showing Corvus comparisons'
branding:
  icon: 'box'
  color: 'purple'
runs:
  using: 'composite'
  steps:
    - name: Checkout ci-corvus
      uses: actions/checkout@v4
      with: 
        repository: nwxrichardson/ci-corvus
    - name: Docker
      run : docker build -t ci-corvus:latest . 
      shell: bash
#    - name: Checkout current repo
#      uses: actions/checkout@v4
    - name: List
      run : ls
      shell: bash
    - name: Docker run
      run : docker run -v /bundles/uk.ac.york.ci.corvus/:/example ci-corvus:latest
      shell: bash
  
