name: 'corvus-comment'
description: 'Generate a comment showing Corvus comparisons'
branding:
  icon: 'box'
  color: 'purple'
runs:
  using: 'docker'
    image: 'Dockerfile'
    volumes:
          - ${{ github.workspace }}/bundles/uk.ac.york.ci.corvus/:/example
