name: 'corvus-comment'
description: 'Generate a comment showing Corvus comparisons'
branding:
  icon: 'box'
  color: 'purple'
runs:
  using: docker
  jobs:
    build-and-run:
      runs-on: ubuntu-latest
      
      steps:
      - name: Build Docker image
        run: |
          docker build -t ci-corvus:latest .
       
      - name: Run Docker container
        run: |
          docker run ci-corvus:latest
