name: 'corvus-comment'
description: 'Generate a comment showing Corvus comparisons'
branding:
  icon: 'box'
  color: 'purple'
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with: 
        repository: nwxrichardson/ci-corvus
    - name: List
      run : ls
      shell: bash
    - name: Docker
      run : docker build -t ci-corvus:latest . 
      shell: bash
  
