name: 'corvus-comment'
description: 'Generate a comment showing Corvus comparisons'
branding:
  icon: 'box'
  color: 'purple'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v6
        with:
          tags: nwxrichardson/ci-corvus:latest
        env:
          SOURCE_DATE_EPOCH: 0
