name: 'corvus-comment'
description: 'Generate a comment showing Corvus comparisons'
branding:
  icon: 'box'
  color: 'purple'
runs:
  using: 'composite'
  steps:
    - name: Checkout ci-corvus
      uses: actions/checkout@v4
      with: 
        repository: nwxrichardson/ci-corvus
    - name: Checkout ci-corvus
      uses: actions/checkout@v4
      with: 
        repository: epsilonlabs/sirius-pr-action-workspace
        path: model/new
        sparse-checkout-cone-mode: 'false'
        sparse-checkout: |
          bundles/psl.example
    - name: Checkout ci-corvus
      uses: actions/checkout@v4
      with: 
        repository: epsilonlabs/sirius-pr-action-workspace
        path: model/old
        ref: main
        sparse-checkout-cone-mode: 'false'
        sparse-checkout: |
          bundles/psl.example
    - name: Docker run
      run : tree
      shell: bash
    - name: Docker
      run : docker build -t ci-corvus:latest . 
      shell: bash
    - name: Docker run
      run : docker run -v $(pwd)/new-model/bundles/psl.example:/example ci-corvus:latest
      shell: bash
    - name: Docker run
      run : tree
      shell: bash
#    - name: Upload README to S3
#      run: |
#          aws s3 cp $(pwd)/bundles/uk.ac.york.ci.corvus/image.png s3://${{ env.BUCKET_NAME }}/
#      shell: bash  
    - name: Create comment from markdown file
      uses: GrantBirki/comment@v2.1.1
      with:
        file: new-model/bundles/psl.example/plain-sample.md
