name: 'Comment on PR'
description: 'Comment on PR'
branding:
  icon: 'box'
  color: 'purple'
inputs:
  github-token: 
    description: 'A token'
    required: true
runs:
  using: node20
  main: dist/index.js
