name: 'corvus-comment'
description: 'Generate a comment showing Corvus comparisons'
branding:
  icon: 'box'
  color: 'purple'
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Docker
      uses: addnab/docker-run-action@v3
        with:
          image: 'Dockerfile'
          options: -v ${{ github.workspace }}:/var/www
  
