name: 'corvus-comment'
description: 'Generate a comment showing Corvus comparisons'
branding:
  icon: 'box'
  color: 'purple'
runs:
  using: 'composite'
  steps:
    - name: Checkout ci-corvus
      uses: actions/checkout@v4
      with: 
        repository: nwxrichardson/ci-corvus
    - name: Docker
      run : docker build -t ci-corvus:latest . 
      shell: bash
#    - name: Checkout current repo
#      uses: actions/checkout@v4
    - name: List
      run : ls
      shell: bash
    - name: Docker run
      run : docker run -v $(pwd)/bundles/uk.ac.york.ci.corvus/:/example ci-corvus:latest
      shell: bash
    - name: Generate API module
      run: |
        git clone https://user:$GITHUB_TOKEN@github.com/epsilonlabs/sirius-pr-action # This works

        cd sirius-pr-action
        git config nwxrichardson "user"

        touch image.png
        git add image.png
        git commit -m "Add new file"
      shell: bash
    - name: Create comment from markdown file
      uses: GrantBirki/comment@v2.1.1
      with:
        file: test/plain-sample.md
