name: 'corvus-comment
description: 'Generate a comment showing Corvus comparisons'
branding:
  icon: 'box'
  color: 'purple'
inputs:
  github-token: 
    description: 'A token'
    required: true
runs:
  using: docker
  image: 'Dockerfile'
  args:
    - ${{ inputs.github-token }}
