name: 'corvus-comment'
description: 'Generate a comment showing Corvus comparisons'
inputs: 
  aird-location:
    description: 'The location that the aird is currently'
    default: ''
branding:
  icon: 'box'
  color: 'purple'
runs:
  using: 'composite'
  steps:
    - name: Checkout ci-corvus
      uses: actions/checkout@v4
      with: 
        repository: nwxrichardson/ci-corvus
    - name: Checkout ci-corvus
      uses: actions/checkout@v4
      with: 
        repository: epsilonlabs/sirius-pr-action-workspace
        sparse-checkout: '${{ inputs.aird-location }}'
        path: model/new        
    - name: Checkout ci-corvus
      uses: actions/checkout@v4
      with: 
        repository: epsilonlabs/sirius-pr-action-workspace
        sparse-checkout: '${{ inputs.aird-location }}'
        path: model/old
        ref: main
    - name: Docker run
      run : docker run -v $(pwd)/output:/output/ -v $(pwd)/model/new/${{ inputs.aird-location }}:/example/new -v $(pwd)/model/old/${{ inputs.aird-location }}:/example/old nwrichardson/ci-corvus:latest
      shell: bash
#    - name: Upload README to S3
#      run: |
#          aws s3 cp --recursive $(pwd)/output/model/ s3://${{ env.BUCKET_NAME }}/model
#      shell: bash  
    - name: Tree
      run : tree
      shell: bash
    - name: Edit md name
      run : sed '1b\${{ github.sha }}' $(pwd)/output/plain-sample.md > $(pwd)/comment.md
      shell: bash
    - name: Create comment from markdown file
      uses: GrantBirki/comment@v2.1.1
      with:
        file: comment.md
