name: 'corvus-comment'
description: 'Generate a comment showing Corvus comparisons'
branding:
  icon: 'box'
  color: 'purple'
runs:
  using: 'composite'
    - name: Checkout
        uses: actions/checkout@v4
    - name: Docker
      container:
      image: 'Dockerfile'
